// ────────── Mock Threats ──────────

export const mockThreats = [
  {
    id: "thr_001",
    ipAddress: "185.220.101.42",
    ipPartial: "185.220.***",
    firstSeen: new Date("2024-06-20T08:30:00Z"),
    lastSeen: new Date("2024-06-24T14:22:00Z"),
    totalEvents: 47,
    threatScore: 87,
    attackerType: "Automated Scanner",
    status: "ACTIVE" as const,
    osGuess: "Linux (Kali)",
    toolchain: ["nmap", "hydra", "gobuster"],
    country: "Germany",
    city: "Frankfurt",
    asn: "AS205100",
    radarScores: { persistence: 72, stealth: 34, sophistication: 61, intent: 89 },
    llmAnalysis: null,
    rawFingerprint: {},
  },
  {
    id: "thr_002",
    ipAddress: "103.253.41.98",
    ipPartial: "103.253.***",
    firstSeen: new Date("2024-06-22T19:15:00Z"),
    lastSeen: new Date("2024-06-24T11:30:00Z"),
    totalEvents: 12,
    threatScore: 94,
    attackerType: "Targeted Human",
    status: "LURED" as const,
    osGuess: "Linux (Ubuntu)",
    toolchain: ["ssh", "scp", "curl", "python3"],
    country: "Russia",
    city: "Moscow",
    asn: "AS49505",
    radarScores: { persistence: 91, stealth: 88, sophistication: 85, intent: 96 },
    llmAnalysis: null,
    rawFingerprint: {},
  },
  {
    id: "thr_003",
    ipAddress: "45.33.32.156",
    ipPartial: "45.33.***",
    firstSeen: new Date("2024-06-23T03:45:00Z"),
    lastSeen: new Date("2024-06-23T03:52:00Z"),
    totalEvents: 156,
    threatScore: 42,
    attackerType: "Script Kiddie",
    status: "BLOCKED" as const,
    osGuess: "Windows 11",
    toolchain: ["metasploit", "nmap"],
    country: "United States",
    city: "Los Angeles",
    asn: "AS63949",
    radarScores: { persistence: 22, stealth: 15, sophistication: 28, intent: 55 },
    llmAnalysis: null,
    rawFingerprint: {},
  },
  {
    id: "thr_004",
    ipAddress: "91.121.209.77",
    ipPartial: "91.121.***",
    firstSeen: new Date("2024-06-18T11:20:00Z"),
    lastSeen: new Date("2024-06-24T16:05:00Z"),
    totalEvents: 8,
    threatScore: 98,
    attackerType: "Nation State Indicator",
    status: "TRAPPED" as const,
    osGuess: "Linux (Custom)",
    toolchain: ["custom-c2", "mimikatz", "bloodhound", "cobalt-strike"],
    country: "China",
    city: "Beijing",
    asn: "AS4808",
    radarScores: { persistence: 97, stealth: 95, sophistication: 99, intent: 100 },
    llmAnalysis: null,
    rawFingerprint: {},
  },
  {
    id: "thr_005",
    ipAddress: "192.168.10.55",
    ipPartial: "192.168.***",
    firstSeen: new Date("2024-06-24T10:00:00Z"),
    lastSeen: new Date("2024-06-24T10:15:00Z"),
    totalEvents: 5,
    threatScore: 15,
    attackerType: "Red Team",
    status: "RESOLVED" as const,
    osGuess: "macOS",
    toolchain: ["burpsuite", "ffuf"],
    country: "United States",
    city: "San Francisco",
    asn: "Internal",
    radarScores: { persistence: 10, stealth: 70, sophistication: 65, intent: 5 },
    llmAnalysis: null,
    rawFingerprint: {},
  },
];

// ────────── Mock Honeypots ──────────

export const mockHoneypots = [
  {
    id: "hp_001",
    name: "prod-ssh-decoy-01",
    type: "SSH" as const,
    port: 22,
    status: "ACTIVE" as const,
    description: "SSH honeypot mimicking production jump server",
    totalHits: 234,
    deployedAt: new Date("2024-06-01T00:00:00Z"),
    config: { banner: "OpenSSH_8.9p1 Ubuntu-3ubuntu0.7" },
  },
  {
    id: "hp_002",
    name: "api-gateway-decoy",
    type: "API" as const,
    port: 8080,
    status: "ACTIVE" as const,
    description: "REST API honeypot with fake user endpoints",
    totalHits: 89,
    deployedAt: new Date("2024-06-05T00:00:00Z"),
    config: { endpoints: ["/api/users", "/api/admin", "/api/tokens"] },
  },
  {
    id: "hp_003",
    name: "mail-server-trap",
    type: "SMTP" as const,
    port: 25,
    status: "ACTIVE" as const,
    description: "SMTP relay honeypot to catch spam relays",
    totalHits: 567,
    deployedAt: new Date("2024-06-03T00:00:00Z"),
    config: { domain: "mail.internal.example.com" },
  },
  {
    id: "hp_004",
    name: "data-lake-bucket",
    type: "S3" as const,
    port: 443,
    status: "PAUSED" as const,
    description: "S3 bucket honeypot with fake data exports",
    totalHits: 12,
    deployedAt: new Date("2024-06-10T00:00:00Z"),
    config: { bucketName: "company-data-exports-2024" },
  },
  {
    id: "hp_005",
    name: "postgres-analytics-db",
    type: "DATABASE" as const,
    port: 5432,
    status: "ACTIVE" as const,
    description: "PostgreSQL honeypot with synthetic analytics data",
    totalHits: 45,
    deployedAt: new Date("2024-06-08T00:00:00Z"),
    config: { dbName: "analytics_prod", tables: ["users", "transactions", "api_keys"] },
  },
];

// ────────── Mock Events ──────────

export const mockEvents = [
  {
    id: "evt_001",
    honeypotId: "hp_001",
    threatId: "thr_001",
    eventType: "AUTH_ATTEMPT" as const,
    timestamp: new Date("2024-06-24T14:22:00Z"),
    payload: { username: "root", password: "admin123" },
    severity: "HIGH" as const,
    honeypotName: "prod-ssh-decoy-01",
  },
  {
    id: "evt_002",
    honeypotId: "hp_002",
    threatId: "thr_002",
    eventType: "CONNECTION" as const,
    timestamp: new Date("2024-06-24T14:18:00Z"),
    payload: { method: "GET", path: "/api/admin/users" },
    severity: "MEDIUM" as const,
    honeypotName: "api-gateway-decoy",
  },
  {
    id: "evt_003",
    honeypotId: "hp_001",
    threatId: "thr_004",
    eventType: "COMMAND" as const,
    timestamp: new Date("2024-06-24T14:15:00Z"),
    payload: { command: "cat /etc/shadow" },
    severity: "CRITICAL" as const,
    honeypotName: "prod-ssh-decoy-01",
  },
  {
    id: "evt_004",
    honeypotId: "hp_004",
    threatId: "thr_002",
    eventType: "FILE_ACCESS" as const,
    timestamp: new Date("2024-06-24T14:10:00Z"),
    payload: { file: "company-data-exports-2024/customers.csv" },
    severity: "HIGH" as const,
    honeypotName: "data-lake-bucket",
  },
  {
    id: "evt_005",
    honeypotId: null,
    threatId: "thr_002",
    eventType: "CANARY_TRIGGER" as const,
    timestamp: new Date("2024-06-24T14:05:00Z"),
    payload: { tokenType: "URL", label: "admin-credentials-doc" },
    severity: "CRITICAL" as const,
    honeypotName: "Canary Token",
  },
  {
    id: "evt_006",
    honeypotId: "hp_005",
    threatId: "thr_003",
    eventType: "AUTH_ATTEMPT" as const,
    timestamp: new Date("2024-06-24T13:55:00Z"),
    payload: { username: "postgres", password: "postgres" },
    severity: "MEDIUM" as const,
    honeypotName: "postgres-analytics-db",
  },
  {
    id: "evt_007",
    honeypotId: "hp_003",
    threatId: "thr_001",
    eventType: "CONNECTION" as const,
    timestamp: new Date("2024-06-24T13:50:00Z"),
    payload: { from: "scanner@malicious.ru" },
    severity: "LOW" as const,
    honeypotName: "mail-server-trap",
  },
  {
    id: "evt_008",
    honeypotId: "hp_001",
    threatId: "thr_004",
    eventType: "EXFILTRATION" as const,
    timestamp: new Date("2024-06-24T13:45:00Z"),
    payload: { size: "2.4MB", destination: "91.121.209.77:4444" },
    severity: "CRITICAL" as const,
    honeypotName: "prod-ssh-decoy-01",
  },
];

// ────────── Mock Canary Tokens ──────────

export const mockCanaryTokens = [
  {
    id: "ct_001",
    tokenType: "URL" as const,
    label: "admin-credentials-doc",
    triggered: true,
    triggeredAt: new Date("2024-06-24T14:05:00Z"),
    triggeredIp: "103.253.41.98",
    createdAt: new Date("2024-06-01T00:00:00Z"),
  },
  {
    id: "ct_002",
    tokenType: "DNS" as const,
    label: "internal-dns-record",
    triggered: false,
    triggeredAt: null,
    triggeredIp: null,
    createdAt: new Date("2024-06-02T00:00:00Z"),
  },
  {
    id: "ct_003",
    tokenType: "DOCUMENT" as const,
    label: "salary-spreadsheet-2024",
    triggered: true,
    triggeredAt: new Date("2024-06-20T09:30:00Z"),
    triggeredIp: "185.220.101.42",
    createdAt: new Date("2024-06-03T00:00:00Z"),
  },
  {
    id: "ct_004",
    tokenType: "IMAGE" as const,
    label: "network-diagram-png",
    triggered: false,
    triggeredAt: null,
    triggeredIp: null,
    createdAt: new Date("2024-06-05T00:00:00Z"),
  },
];

// ────────── Mock Dashboard Stats ──────────

export const mockDashboardStats = {
  activeHoneypots: 4,
  threatsDetected: 23,
  attackersLured: 7,
  securityScore: 94,
  eventsToday: 34,
  criticalAlerts: 3,
  canaryTokensActive: 4,
  canaryTriggered: 2,
};

// ────────── Mock Analytics Data ──────────

export const mockAnalyticsData = {
  threatsByDay: [
    { date: "Jun 18", threats: 2, events: 12 },
    { date: "Jun 19", threats: 5, events: 28 },
    { date: "Jun 20", threats: 8, events: 45 },
    { date: "Jun 21", threats: 3, events: 19 },
    { date: "Jun 22", threats: 12, events: 67 },
    { date: "Jun 23", threats: 7, events: 38 },
    { date: "Jun 24", threats: 9, events: 52 },
  ],
  threatsByType: [
    { type: "Script Kiddie", count: 45, percentage: 38 },
    { type: "Automated Scanner", count: 32, percentage: 27 },
    { type: "Targeted Human", count: 18, percentage: 15 },
    { type: "Nation State", count: 5, percentage: 4 },
    { type: "Red Team", count: 8, percentage: 7 },
    { type: "Unknown", count: 12, percentage: 10 },
  ],
  honeypotHits: [
    { name: "prod-ssh-decoy-01", hits: 234, type: "SSH" },
    { name: "mail-server-trap", hits: 567, type: "SMTP" },
    { name: "api-gateway-decoy", hits: 89, type: "API" },
    { name: "postgres-analytics-db", hits: 45, type: "DATABASE" },
    { name: "data-lake-bucket", hits: 12, type: "S3" },
  ],
  geoData: [
    { country: "Russia", attacks: 34 },
    { country: "China", attacks: 28 },
    { country: "United States", attacks: 22 },
    { country: "Germany", attacks: 15 },
    { country: "Brazil", attacks: 11 },
    { country: "India", attacks: 8 },
    { country: "Iran", attacks: 6 },
  ],
  severityBreakdown: [
    { severity: "Critical", count: 8, color: "#E24B4A" },
    { severity: "High", count: 23, color: "#F09595" },
    { severity: "Medium", count: 45, color: "#EF9F27" },
    { severity: "Low", count: 67, color: "#85B7EB" },
  ],
};
